### ISSUE TITLE
Update persistance

### ISSUE THREAD

**Issue by Bumpy226** [Jadquir/UnitedAdobeEditor#6]
Would it be possible for the splash screens to persist after updates to the Creative Cloud apps?
This week I had to reapply the Illustrator splash screen twice due to updates.

Haven't tried it, but perhaps making the files read only could work?

**Comment by Jadquir** [comment]
Hello, I don't think that will work because some of the files are resource files so if we were to make them read-only, probably the app would not update correctly. I recently added a config file, maybe I can add a config creator and make it so that when you click it and it changes the splash screen without any selections.
